/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tutorials;

/**
 *
 * @author byarker1
 */
public class UserInterface extends javax.swing.JFrame {
    
    String SELECTVALUE = null;
    
    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonInsertStudent = new javax.swing.JButton();
        labelInsert = new javax.swing.JLabel();
        buttonInsertTutor = new javax.swing.JButton();
        buttonInsertGroup = new javax.swing.JButton();
        labelSelect = new javax.swing.JLabel();
        buttonSelectGroup = new javax.swing.JButton();
        buttonSelectTutees = new javax.swing.JButton();
        textSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setLocation(new java.awt.Point(200, 200));
        setName("frameHome"); // NOI18N

        buttonInsertStudent.setText("Student");

        labelInsert.setText("Insert");

        buttonInsertTutor.setAlignmentY(0.0F);
        buttonInsertTutor.setLabel("Tutor");

        buttonInsertGroup.setText("Tutor Group");
        buttonInsertGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertGroupActionPerformed(evt);
            }
        });

        labelSelect.setText("Select");

        buttonSelectGroup.setText("Group");
        buttonSelectGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectGroupActionPerformed(evt);
            }
        });

        buttonSelectTutees.setText("Tutees");
        buttonSelectTutees.setName("buttonSelectTutees"); // NOI18N
        buttonSelectTutees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectTuteesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(buttonInsertStudent)
                        .addGap(48, 48, 48)
                        .addComponent(buttonInsertTutor)
                        .addGap(47, 47, 47)
                        .addComponent(buttonInsertGroup))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(labelInsert))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(labelSelect))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonSelectGroup)
                                .addGap(77, 77, 77))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)))
                        .addComponent(buttonSelectTutees)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labelInsert)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInsertStudent)
                    .addComponent(buttonInsertTutor)
                    .addComponent(buttonInsertGroup))
                .addGap(30, 30, 30)
                .addComponent(labelSelect)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSelectGroup)
                    .addComponent(buttonSelectTutees))
                .addGap(26, 26, 26)
                .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInsertGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonInsertGroupActionPerformed

    private void buttonSelectTuteesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelectTuteesActionPerformed
        // TODO add your handling code here
        SELECTVALUE = "tutee";
    }//GEN-LAST:event_buttonSelectTuteesActionPerformed

    private void buttonSelectGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelectGroupActionPerformed
        // TODO add your handling code here:
        SELECTVALUE = "group";
    }//GEN-LAST:event_buttonSelectGroupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonInsertGroup;
    private javax.swing.JButton buttonInsertStudent;
    private javax.swing.JButton buttonInsertTutor;
    private javax.swing.JButton buttonSelectGroup;
    private javax.swing.JButton buttonSelectTutees;
    private javax.swing.JLabel labelInsert;
    private javax.swing.JLabel labelSelect;
    private javax.swing.JTextField textSearch;
    // End of variables declaration//GEN-END:variables
}
